#!/bin/bash
echo "🔍 Finding your S3 bucket name..."
echo ""
echo "Your API Gateway: 6wg7m9tsxg.execute-api.us-east-1.amazonaws.com"
echo "Region: us-east-1"
echo ""
echo "To find your bucket name, run these AWS CLI commands:"
echo ""
echo "1. List all Lambda functions in us-east-1:"
echo "   aws lambda list-functions --region us-east-1 --query 'Functions[?contains(FunctionName, \`get\`) || contains(FunctionName, \`parsed\`) || contains(FunctionName, \`transcript\`)].FunctionName' --output table"
echo ""
echo "2. Or list all S3 buckets:"
echo "   aws s3 ls"
echo ""
echo "3. Or check API Gateway stages:"
echo "   aws apigateway get-rest-apis --region us-east-1 --query 'items[?id==\`6wg7m9tsxg\`]'"
echo ""
echo "Look for buckets with names like:"
echo "  - *transcript*"
echo "  - *recording*"
echo "  - *supportiq*"
echo "  - *call-center*"
echo "  - *parsed*"
